Feature: 

	

	@UI-Scenario1
	Scenario: Scenario1 - 
		Given User is on login page for TestCase "UI-Scenario1"
		When Open page "https://www.saucedemo.com/"
		Then Verify Page Title is "Swag Labs"
		Then Verify Default Value of "text" having "id" "user-name" is ""
		Then Verify Placeholder of "text" having "id" "user-name" is "Username"
		Then Enter value "standard_user" in "text" having "id" "user-name"
		Then Verify Default Value of "password" having "id" "password" is ""
		Then Verify Placeholder of "password" having "id" "password" is "Password"
		Then Enter value "secret_sauce" in "password" having "id" "password"
		Then Click element "submit" having "id" "login-button"
		Then Click element "submit" having "id" "add-to-cart-sauce-labs-bolt-t-shirt"
		Then Click element "" having "cssSelector" "a.shopping_cart_link:nth-child(1)"
		Then Click element "submit" having "id" "checkout"
		Then Verify Default Value of "text" having "id" "first-name" is ""
		Then Verify Placeholder of "text" having "id" "first-name" is "First Name"
		Then Verify Default Value of "text" having "id" "first-name" is ""
		Then Verify Placeholder of "text" having "id" "first-name" is "First Name"
		Then Enter value "CE" in "text" having "id" "first-name"
		Then Verify Default Value of "text" having "id" "last-name" is ""
		Then Verify Placeholder of "text" having "id" "last-name" is "Last Name"
		Then Enter value "CETEST" in "text" having "id" "last-name"
		Then Verify Default Value of "text" having "id" "postal-code" is ""
		Then Verify Placeholder of "text" having "id" "postal-code" is "Zip/Postal Code"
		Then Enter value "303020" in "text" having "id" "postal-code"
		Then Click element "submit" having "id" "continue"
		Then Click element "submit" having "id" "finish"
		Then Click element "submit" having "id" "back-to-products"
		Then Click element "" having "cssSelector" "div.header_label:nth-child(2)"
		Then Click element "button" having "id" "react-burger-menu-btn"
		Then Click element "" having "id" "logout_sidebar_link"
